### ISSUE TITLE
Is it possible to disable the screen lighting option?

### ISSUE THREAD

**Issue by chmac** [balau/fakedawn#37]
Firstly, thanks for sharing great software.

Is it possible to use only the sound feature? I couldn't see an option to disable the light option...

**Comment by balau** [comment]
Thanks!
There is no "clean" way to disable light (yet), but you can make the sound start earlier than light, so that the alarm will begin to play but the screen will remain black.
For example if you place the sound start at 6:30AM, the sound maximum at 7:00AM, and the light start at 7:30, then the screen should remain black (unless you take an hour to wake up).
Hope this helps.

**Comment by chmac** [comment]
Awesome, thanks. I'll also try setting the screen light to 0 minutes and see if that works.
